export const EVENTS = [
  {
    slug: "feb-2026-monthly-rideout-west",
    title: "Feb 2026: Monthly Rideout, West",
    date: "2026-02-22",
    time: "10:00",
    location: "Arch 70, Albert Embankment, London SE1 7TP",
    category: "Rideout",
    description: "Join us for our monthly organised rideout heading west. Meet and ride with fellow members and adore all things Ducati. Meet time: 10:00am for a 10:30am departure.",
    image: "/images/rideout-placeholder.jpg",
  },
  {
    slug: "mar-2026-monthly-rideout-north",
    title: "Mar 2026: Monthly Rideout, North",
    date: "2026-03-22",
    time: "10:00",
    location: "Arch 70, Albert Embankment, London SE1 7TP",
    category: "Rideout",
    description: "Official Monthly Rideout – North. Come and join us for one of our organised rideouts heading north.",
    image: "/images/rideout-placeholder.jpg",
  },
  {
    slug: "ridewise-pro-training",
    title: "Ridewise Pro Training",
    date: "2026-03-28",
    time: "09:00",
    location: "Brands Hatch, Longfield, Kent DA3 8NG",
    category: "Training",
    description: "Professional riding skills training day with Ridewise. Open to all members. Limited spaces — members priority booking.",
    image: "/images/training-placeholder.jpg",
  },
  {
    slug: "apr-2026-monthly-rideout-east",
    title: "Apr 2026: Monthly Rideout, East",
    date: "2026-04-19",
    time: "10:00",
    location: "Arch 70, Albert Embankment, London SE1 7TP",
    category: "Rideout",
    description: "Official Monthly Rideout – East. Meet and ride with fellow members.",
    image: "/images/rideout-placeholder.jpg",
  },
  {
    slug: "i-want-to-wheelie",
    title: "I Want to Wheelie!",
    date: "2026-04-25",
    time: "09:00",
    location: "Private track, Kent",
    category: "Training",
    description: "Learn to wheelie in a safe, controlled environment with professional instruction. All bikes welcome.",
    image: "/images/training-placeholder.jpg",
  },
  {
    slug: "may-2026-monthly-rideout-south-club-bbq",
    title: "May 2026: Monthly Rideout South + Club BBQ",
    date: "2026-05-17",
    time: "10:00",
    location: "Arch 70, Albert Embankment, London SE1 7TP",
    category: "Social",
    description: "Our annual spring rideout heading south, followed by a club BBQ back at HQ. Bring your appetite!",
    image: "/images/social-placeholder.jpg",
  },
  {
    slug: "doclse-wdw-2026",
    title: "DOCLSE @ World Ducati Week 2026",
    date: "2026-06-24",
    time: "All day",
    location: "Misano World Circuit, Italy",
    category: "Special",
    description: "Join the DOCLSE crew at World Ducati Week 2026 in Misano, Italy. The ultimate Ducati gathering. Paid member discounts apply.",
    image: "/images/wdw-placeholder.jpg",
  },
  {
    slug: "doclse-christmas-party",
    title: "DOCLSE Christmas Party 2026",
    date: "2026-12-05",
    time: "19:00",
    location: "Arch 70, Albert Embankment, London SE1 7TP",
    category: "Social",
    description: "Our annual Christmas party — food, drinks, awards and good company. Members and guests welcome.",
    image: "/images/social-placeholder.jpg",
  },
];

export const TEAM = [
  { name: "Jonathan Tait", role: "President", bio: "Founder and driving force behind DOCLSE. Passionate Ducatista and experienced rider." },
  { name: "Rob Furlong", role: "Vice President & Social Media", bio: "Keeping the club connected online and helping steer the ship." },
  { name: "Roberta Tait", role: "Treasurer", bio: "Keeping the club's finances in order with precision and care." },
  { name: "Alan Wright", role: "Secretary", bio: "The organisational backbone of the club." },
  { name: "Chris Bird", role: "Events", bio: "Planning and executing all the amazing club events and rideouts." },
  { name: "Mark Speller", role: "Sponsorship & Partnerships", bio: "Building relationships with brands and partners to bring member value." },
];

export const PRODUCTS = [
  {
    slug: "doclse-beanie",
    name: "DOCLSE Beanie",
    price: 1800,
    description: "Official DOCLSE beanie hat. One size fits all. Available in black with red DOCLSE logo embroidery.",
    images: ["/images/beanie-1.jpg", "/images/beanie-2.jpg"],
    category: "Accessories",
    inStock: true,
  },
  {
    slug: "doclse-cap",
    name: "DOCLSE Cap",
    price: 2000,
    description: "Official DOCLSE cap. Adjustable strap. Black with embroidered red DOCLSE logo.",
    images: ["/images/cap-1.jpg", "/images/cap-2.jpg"],
    category: "Clothing",
    inStock: true,
  },
];

export const MEMBERSHIP_PLANS = [
  {
    id: "subscriber",
    name: "Subscriber",
    price: 0,
    period: "Free",
    description: "Get started with DOCLSE. Access to public events and club updates.",
    features: [
      "Access to all public events",
      "Club newsletter",
      "DOCLSE community access",
      "Event notifications",
    ],
    highlight: false,
  },
  {
    id: "paid",
    name: "Full Member",
    price: 3000,
    period: "per year",
    description: "Full membership with exclusive benefits, discounts and priority booking.",
    features: [
      "Everything in Subscriber",
      "Priority event booking",
      "Exclusive member discounts (15%+ partners)",
      "La Passione club magazine",
      "World Ducati Week group discount",
      "Member-only rideouts",
      "Voting rights at AGM",
      "Digital membership card",
    ],
    highlight: true,
  },
];

export const RIDE_REPORTS = [
  {
    slug: "fish-chips-by-the-sea",
    title: "Fish & Chips by the Sea",
    date: "2024-08-18",
    author: "David Lee",
    excerpt: "A cracking summer rideout down to the coast for fish & chips. Read about the route, the laughs and the Ducatis.",
    image: "/images/report-1.jpg",
    category: "Ride Report",
  },
  {
    slug: "end-of-summer-picnic-ride",
    title: "End of Summer Picnic Ride",
    date: "2024-09-08",
    author: "Jonathan Tait",
    excerpt: "We said goodbye to summer in style — a scenic loop through the Surrey Hills and a picnic stop in the countryside.",
    image: "/images/report-2.jpg",
    category: "Ride Report",
  },
  {
    slug: "down-to-the-coast",
    title: "Down to the Coast",
    date: "2024-08-04",
    author: "Chloe",
    excerpt: "One of those perfect riding days. Blue skies, twisty roads and the smell of the sea.",
    image: "/images/report-3.jpg",
    category: "Ride Report",
  },
  {
    slug: "wet-ride-to-westerham",
    title: "Wet Ride to Westerham",
    date: "2024-07-14",
    author: "Jonathan Tait",
    excerpt: "Not every ride is sunshine. A soggy but memorable run to Westerham — proof that Ducatistas ride in all weathers.",
    image: "/images/report-4.jpg",
    category: "Ride Report",
  },
  {
    slug: "inaugural-ride-and-meet",
    title: "Inaugural Ride and Meet",
    date: "2024-06-02",
    author: "Jonathan Tait",
    excerpt: "The very first DOCLSE rideout. A moment in history for the club — a small group, a big dream.",
    image: "/images/report-5.jpg",
    category: "Ride Report",
  },
  {
    slug: "panigale-v2-review",
    title: "Panigale V2 Review",
    date: "2025-03-10",
    author: "Mark Speller",
    excerpt: "We got our hands on the MY25 Panigale V2. Here's what we thought after a day at the track.",
    image: "/images/report-review.jpg",
    category: "Review",
  },
];

export const DISCOUNTS = [
  { partner: "Ducati London", discount: "10% off parts & accessories", category: "Dealership" },
  { partner: "Ridewise Training", discount: "15% off all training courses", category: "Training" },
  { partner: "Feridax", discount: "10% off clothing & luggage", category: "Gear" },
  { partner: "Datatag", discount: "Free registration + 20% off kits", category: "Security" },
  { partner: "Fowlers of Bristol", discount: "5% off parts online", category: "Parts" },
  { partner: "Bickers Action", discount: "10% off clothing", category: "Gear" },
];
